# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pzhang/chen/permeable_bed

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pzhang/chen/permeable_bed

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pzhang/chen/permeable_bed/CMakeFiles /home/pzhang/chen/permeable_bed/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pzhang/chen/permeable_bed/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named temp

# Build rule for target.
temp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 temp
.PHONY : temp

# fast build rule for target.
temp/fast:
	$(MAKE) -f CMakeFiles/temp.dir/build.make CMakeFiles/temp.dir/build
.PHONY : temp/fast

#=============================================================================
# Target rules for targets named test_sc_ga

# Build rule for target.
test_sc_ga: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sc_ga
.PHONY : test_sc_ga

# fast build rule for target.
test_sc_ga/fast:
	$(MAKE) -f CMakeFiles/test_sc_ga.dir/build.make CMakeFiles/test_sc_ga.dir/build
.PHONY : test_sc_ga/fast

#=============================================================================
# Target rules for targets named test_bb

# Build rule for target.
test_bb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bb
.PHONY : test_bb

# fast build rule for target.
test_bb/fast:
	$(MAKE) -f CMakeFiles/test_bb.dir/build.make CMakeFiles/test_bb.dir/build
.PHONY : test_bb/fast

#=============================================================================
# Target rules for targets named test_ibm2

# Build rule for target.
test_ibm2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ibm2
.PHONY : test_ibm2

# fast build rule for target.
test_ibm2/fast:
	$(MAKE) -f CMakeFiles/test_ibm2.dir/build.make CMakeFiles/test_ibm2.dir/build
.PHONY : test_ibm2/fast

#=============================================================================
# Target rules for targets named test_sc_bb

# Build rule for target.
test_sc_bb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sc_bb
.PHONY : test_sc_bb

# fast build rule for target.
test_sc_bb/fast:
	$(MAKE) -f CMakeFiles/test_sc_bb.dir/build.make CMakeFiles/test_sc_bb.dir/build
.PHONY : test_sc_bb/fast

#=============================================================================
# Target rules for targets named test_cd_bb

# Build rule for target.
test_cd_bb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cd_bb
.PHONY : test_cd_bb

# fast build rule for target.
test_cd_bb/fast:
	$(MAKE) -f CMakeFiles/test_cd_bb.dir/build.make CMakeFiles/test_cd_bb.dir/build
.PHONY : test_cd_bb/fast

#=============================================================================
# Target rules for targets named test_sc_ibm

# Build rule for target.
test_sc_ibm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sc_ibm
.PHONY : test_sc_ibm

# fast build rule for target.
test_sc_ibm/fast:
	$(MAKE) -f CMakeFiles/test_sc_ibm.dir/build.make CMakeFiles/test_sc_ibm.dir/build
.PHONY : test_sc_ibm/fast

#=============================================================================
# Target rules for targets named test_cd_ga

# Build rule for target.
test_cd_ga: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cd_ga
.PHONY : test_cd_ga

# fast build rule for target.
test_cd_ga/fast:
	$(MAKE) -f CMakeFiles/test_cd_ga.dir/build.make CMakeFiles/test_cd_ga.dir/build
.PHONY : test_cd_ga/fast

#=============================================================================
# Target rules for targets named test_ibm

# Build rule for target.
test_ibm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ibm
.PHONY : test_ibm

# fast build rule for target.
test_ibm/fast:
	$(MAKE) -f CMakeFiles/test_ibm.dir/build.make CMakeFiles/test_ibm.dir/build
.PHONY : test_ibm/fast

#=============================================================================
# Target rules for targets named test_spheres_bb

# Build rule for target.
test_spheres_bb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_spheres_bb
.PHONY : test_spheres_bb

# fast build rule for target.
test_spheres_bb/fast:
	$(MAKE) -f CMakeFiles/test_spheres_bb.dir/build.make CMakeFiles/test_spheres_bb.dir/build
.PHONY : test_spheres_bb/fast

#=============================================================================
# Target rules for targets named test_ga

# Build rule for target.
test_ga: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ga
.PHONY : test_ga

# fast build rule for target.
test_ga/fast:
	$(MAKE) -f CMakeFiles/test_ga.dir/build.make CMakeFiles/test_ga.dir/build
.PHONY : test_ga/fast

#=============================================================================
# Target rules for targets named test_ibm3

# Build rule for target.
test_ibm3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ibm3
.PHONY : test_ibm3

# fast build rule for target.
test_ibm3/fast:
	$(MAKE) -f CMakeFiles/test_ibm3.dir/build.make CMakeFiles/test_ibm3.dir/build
.PHONY : test_ibm3/fast

temp.o: temp.cpp.o

.PHONY : temp.o

# target to build an object file
temp.cpp.o:
	$(MAKE) -f CMakeFiles/temp.dir/build.make CMakeFiles/temp.dir/temp.cpp.o
.PHONY : temp.cpp.o

temp.i: temp.cpp.i

.PHONY : temp.i

# target to preprocess a source file
temp.cpp.i:
	$(MAKE) -f CMakeFiles/temp.dir/build.make CMakeFiles/temp.dir/temp.cpp.i
.PHONY : temp.cpp.i

temp.s: temp.cpp.s

.PHONY : temp.s

# target to generate assembly for a file
temp.cpp.s:
	$(MAKE) -f CMakeFiles/temp.dir/build.make CMakeFiles/temp.dir/temp.cpp.s
.PHONY : temp.cpp.s

test_bb.o: test_bb.cpp.o

.PHONY : test_bb.o

# target to build an object file
test_bb.cpp.o:
	$(MAKE) -f CMakeFiles/test_bb.dir/build.make CMakeFiles/test_bb.dir/test_bb.cpp.o
.PHONY : test_bb.cpp.o

test_bb.i: test_bb.cpp.i

.PHONY : test_bb.i

# target to preprocess a source file
test_bb.cpp.i:
	$(MAKE) -f CMakeFiles/test_bb.dir/build.make CMakeFiles/test_bb.dir/test_bb.cpp.i
.PHONY : test_bb.cpp.i

test_bb.s: test_bb.cpp.s

.PHONY : test_bb.s

# target to generate assembly for a file
test_bb.cpp.s:
	$(MAKE) -f CMakeFiles/test_bb.dir/build.make CMakeFiles/test_bb.dir/test_bb.cpp.s
.PHONY : test_bb.cpp.s

test_cd_bb.o: test_cd_bb.cpp.o

.PHONY : test_cd_bb.o

# target to build an object file
test_cd_bb.cpp.o:
	$(MAKE) -f CMakeFiles/test_cd_bb.dir/build.make CMakeFiles/test_cd_bb.dir/test_cd_bb.cpp.o
.PHONY : test_cd_bb.cpp.o

test_cd_bb.i: test_cd_bb.cpp.i

.PHONY : test_cd_bb.i

# target to preprocess a source file
test_cd_bb.cpp.i:
	$(MAKE) -f CMakeFiles/test_cd_bb.dir/build.make CMakeFiles/test_cd_bb.dir/test_cd_bb.cpp.i
.PHONY : test_cd_bb.cpp.i

test_cd_bb.s: test_cd_bb.cpp.s

.PHONY : test_cd_bb.s

# target to generate assembly for a file
test_cd_bb.cpp.s:
	$(MAKE) -f CMakeFiles/test_cd_bb.dir/build.make CMakeFiles/test_cd_bb.dir/test_cd_bb.cpp.s
.PHONY : test_cd_bb.cpp.s

test_cd_ga.o: test_cd_ga.cpp.o

.PHONY : test_cd_ga.o

# target to build an object file
test_cd_ga.cpp.o:
	$(MAKE) -f CMakeFiles/test_cd_ga.dir/build.make CMakeFiles/test_cd_ga.dir/test_cd_ga.cpp.o
.PHONY : test_cd_ga.cpp.o

test_cd_ga.i: test_cd_ga.cpp.i

.PHONY : test_cd_ga.i

# target to preprocess a source file
test_cd_ga.cpp.i:
	$(MAKE) -f CMakeFiles/test_cd_ga.dir/build.make CMakeFiles/test_cd_ga.dir/test_cd_ga.cpp.i
.PHONY : test_cd_ga.cpp.i

test_cd_ga.s: test_cd_ga.cpp.s

.PHONY : test_cd_ga.s

# target to generate assembly for a file
test_cd_ga.cpp.s:
	$(MAKE) -f CMakeFiles/test_cd_ga.dir/build.make CMakeFiles/test_cd_ga.dir/test_cd_ga.cpp.s
.PHONY : test_cd_ga.cpp.s

test_ga.o: test_ga.cpp.o

.PHONY : test_ga.o

# target to build an object file
test_ga.cpp.o:
	$(MAKE) -f CMakeFiles/test_ga.dir/build.make CMakeFiles/test_ga.dir/test_ga.cpp.o
.PHONY : test_ga.cpp.o

test_ga.i: test_ga.cpp.i

.PHONY : test_ga.i

# target to preprocess a source file
test_ga.cpp.i:
	$(MAKE) -f CMakeFiles/test_ga.dir/build.make CMakeFiles/test_ga.dir/test_ga.cpp.i
.PHONY : test_ga.cpp.i

test_ga.s: test_ga.cpp.s

.PHONY : test_ga.s

# target to generate assembly for a file
test_ga.cpp.s:
	$(MAKE) -f CMakeFiles/test_ga.dir/build.make CMakeFiles/test_ga.dir/test_ga.cpp.s
.PHONY : test_ga.cpp.s

test_ibm.o: test_ibm.cpp.o

.PHONY : test_ibm.o

# target to build an object file
test_ibm.cpp.o:
	$(MAKE) -f CMakeFiles/test_ibm.dir/build.make CMakeFiles/test_ibm.dir/test_ibm.cpp.o
.PHONY : test_ibm.cpp.o

test_ibm.i: test_ibm.cpp.i

.PHONY : test_ibm.i

# target to preprocess a source file
test_ibm.cpp.i:
	$(MAKE) -f CMakeFiles/test_ibm.dir/build.make CMakeFiles/test_ibm.dir/test_ibm.cpp.i
.PHONY : test_ibm.cpp.i

test_ibm.s: test_ibm.cpp.s

.PHONY : test_ibm.s

# target to generate assembly for a file
test_ibm.cpp.s:
	$(MAKE) -f CMakeFiles/test_ibm.dir/build.make CMakeFiles/test_ibm.dir/test_ibm.cpp.s
.PHONY : test_ibm.cpp.s

test_ibm2.o: test_ibm2.cpp.o

.PHONY : test_ibm2.o

# target to build an object file
test_ibm2.cpp.o:
	$(MAKE) -f CMakeFiles/test_ibm2.dir/build.make CMakeFiles/test_ibm2.dir/test_ibm2.cpp.o
.PHONY : test_ibm2.cpp.o

test_ibm2.i: test_ibm2.cpp.i

.PHONY : test_ibm2.i

# target to preprocess a source file
test_ibm2.cpp.i:
	$(MAKE) -f CMakeFiles/test_ibm2.dir/build.make CMakeFiles/test_ibm2.dir/test_ibm2.cpp.i
.PHONY : test_ibm2.cpp.i

test_ibm2.s: test_ibm2.cpp.s

.PHONY : test_ibm2.s

# target to generate assembly for a file
test_ibm2.cpp.s:
	$(MAKE) -f CMakeFiles/test_ibm2.dir/build.make CMakeFiles/test_ibm2.dir/test_ibm2.cpp.s
.PHONY : test_ibm2.cpp.s

test_ibm3.o: test_ibm3.cpp.o

.PHONY : test_ibm3.o

# target to build an object file
test_ibm3.cpp.o:
	$(MAKE) -f CMakeFiles/test_ibm3.dir/build.make CMakeFiles/test_ibm3.dir/test_ibm3.cpp.o
.PHONY : test_ibm3.cpp.o

test_ibm3.i: test_ibm3.cpp.i

.PHONY : test_ibm3.i

# target to preprocess a source file
test_ibm3.cpp.i:
	$(MAKE) -f CMakeFiles/test_ibm3.dir/build.make CMakeFiles/test_ibm3.dir/test_ibm3.cpp.i
.PHONY : test_ibm3.cpp.i

test_ibm3.s: test_ibm3.cpp.s

.PHONY : test_ibm3.s

# target to generate assembly for a file
test_ibm3.cpp.s:
	$(MAKE) -f CMakeFiles/test_ibm3.dir/build.make CMakeFiles/test_ibm3.dir/test_ibm3.cpp.s
.PHONY : test_ibm3.cpp.s

test_sc_bb.o: test_sc_bb.cpp.o

.PHONY : test_sc_bb.o

# target to build an object file
test_sc_bb.cpp.o:
	$(MAKE) -f CMakeFiles/test_sc_bb.dir/build.make CMakeFiles/test_sc_bb.dir/test_sc_bb.cpp.o
.PHONY : test_sc_bb.cpp.o

test_sc_bb.i: test_sc_bb.cpp.i

.PHONY : test_sc_bb.i

# target to preprocess a source file
test_sc_bb.cpp.i:
	$(MAKE) -f CMakeFiles/test_sc_bb.dir/build.make CMakeFiles/test_sc_bb.dir/test_sc_bb.cpp.i
.PHONY : test_sc_bb.cpp.i

test_sc_bb.s: test_sc_bb.cpp.s

.PHONY : test_sc_bb.s

# target to generate assembly for a file
test_sc_bb.cpp.s:
	$(MAKE) -f CMakeFiles/test_sc_bb.dir/build.make CMakeFiles/test_sc_bb.dir/test_sc_bb.cpp.s
.PHONY : test_sc_bb.cpp.s

test_sc_ga.o: test_sc_ga.cpp.o

.PHONY : test_sc_ga.o

# target to build an object file
test_sc_ga.cpp.o:
	$(MAKE) -f CMakeFiles/test_sc_ga.dir/build.make CMakeFiles/test_sc_ga.dir/test_sc_ga.cpp.o
.PHONY : test_sc_ga.cpp.o

test_sc_ga.i: test_sc_ga.cpp.i

.PHONY : test_sc_ga.i

# target to preprocess a source file
test_sc_ga.cpp.i:
	$(MAKE) -f CMakeFiles/test_sc_ga.dir/build.make CMakeFiles/test_sc_ga.dir/test_sc_ga.cpp.i
.PHONY : test_sc_ga.cpp.i

test_sc_ga.s: test_sc_ga.cpp.s

.PHONY : test_sc_ga.s

# target to generate assembly for a file
test_sc_ga.cpp.s:
	$(MAKE) -f CMakeFiles/test_sc_ga.dir/build.make CMakeFiles/test_sc_ga.dir/test_sc_ga.cpp.s
.PHONY : test_sc_ga.cpp.s

test_sc_ibm.o: test_sc_ibm.cpp.o

.PHONY : test_sc_ibm.o

# target to build an object file
test_sc_ibm.cpp.o:
	$(MAKE) -f CMakeFiles/test_sc_ibm.dir/build.make CMakeFiles/test_sc_ibm.dir/test_sc_ibm.cpp.o
.PHONY : test_sc_ibm.cpp.o

test_sc_ibm.i: test_sc_ibm.cpp.i

.PHONY : test_sc_ibm.i

# target to preprocess a source file
test_sc_ibm.cpp.i:
	$(MAKE) -f CMakeFiles/test_sc_ibm.dir/build.make CMakeFiles/test_sc_ibm.dir/test_sc_ibm.cpp.i
.PHONY : test_sc_ibm.cpp.i

test_sc_ibm.s: test_sc_ibm.cpp.s

.PHONY : test_sc_ibm.s

# target to generate assembly for a file
test_sc_ibm.cpp.s:
	$(MAKE) -f CMakeFiles/test_sc_ibm.dir/build.make CMakeFiles/test_sc_ibm.dir/test_sc_ibm.cpp.s
.PHONY : test_sc_ibm.cpp.s

test_spheres_bb.o: test_spheres_bb.cpp.o

.PHONY : test_spheres_bb.o

# target to build an object file
test_spheres_bb.cpp.o:
	$(MAKE) -f CMakeFiles/test_spheres_bb.dir/build.make CMakeFiles/test_spheres_bb.dir/test_spheres_bb.cpp.o
.PHONY : test_spheres_bb.cpp.o

test_spheres_bb.i: test_spheres_bb.cpp.i

.PHONY : test_spheres_bb.i

# target to preprocess a source file
test_spheres_bb.cpp.i:
	$(MAKE) -f CMakeFiles/test_spheres_bb.dir/build.make CMakeFiles/test_spheres_bb.dir/test_spheres_bb.cpp.i
.PHONY : test_spheres_bb.cpp.i

test_spheres_bb.s: test_spheres_bb.cpp.s

.PHONY : test_spheres_bb.s

# target to generate assembly for a file
test_spheres_bb.cpp.s:
	$(MAKE) -f CMakeFiles/test_spheres_bb.dir/build.make CMakeFiles/test_spheres_bb.dir/test_spheres_bb.cpp.s
.PHONY : test_spheres_bb.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... temp"
	@echo "... test_sc_ga"
	@echo "... test_bb"
	@echo "... test_ibm2"
	@echo "... test_sc_bb"
	@echo "... test_cd_bb"
	@echo "... test_sc_ibm"
	@echo "... test_cd_ga"
	@echo "... test_ibm"
	@echo "... test_spheres_bb"
	@echo "... test_ga"
	@echo "... test_ibm3"
	@echo "... temp.o"
	@echo "... temp.i"
	@echo "... temp.s"
	@echo "... test_bb.o"
	@echo "... test_bb.i"
	@echo "... test_bb.s"
	@echo "... test_cd_bb.o"
	@echo "... test_cd_bb.i"
	@echo "... test_cd_bb.s"
	@echo "... test_cd_ga.o"
	@echo "... test_cd_ga.i"
	@echo "... test_cd_ga.s"
	@echo "... test_ga.o"
	@echo "... test_ga.i"
	@echo "... test_ga.s"
	@echo "... test_ibm.o"
	@echo "... test_ibm.i"
	@echo "... test_ibm.s"
	@echo "... test_ibm2.o"
	@echo "... test_ibm2.i"
	@echo "... test_ibm2.s"
	@echo "... test_ibm3.o"
	@echo "... test_ibm3.i"
	@echo "... test_ibm3.s"
	@echo "... test_sc_bb.o"
	@echo "... test_sc_bb.i"
	@echo "... test_sc_bb.s"
	@echo "... test_sc_ga.o"
	@echo "... test_sc_ga.i"
	@echo "... test_sc_ga.s"
	@echo "... test_sc_ibm.o"
	@echo "... test_sc_ibm.i"
	@echo "... test_sc_ibm.s"
	@echo "... test_spheres_bb.o"
	@echo "... test_spheres_bb.i"
	@echo "... test_spheres_bb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

