# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pzhang/chen/permeable_bed

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pzhang/chen/permeable_bed

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pzhang/chen/permeable_bed/CMakeFiles /home/pzhang/chen/permeable_bed/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pzhang/chen/permeable_bed/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_cavity

# Build rule for target.
test_cavity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cavity
.PHONY : test_cavity

# fast build rule for target.
test_cavity/fast:
	$(MAKE) -f CMakeFiles/test_cavity.dir/build.make CMakeFiles/test_cavity.dir/build
.PHONY : test_cavity/fast

#=============================================================================
# Target rules for targets named test_carve2

# Build rule for target.
test_carve2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_carve2
.PHONY : test_carve2

# fast build rule for target.
test_carve2/fast:
	$(MAKE) -f CMakeFiles/test_carve2.dir/build.make CMakeFiles/test_carve2.dir/build
.PHONY : test_carve2/fast

#=============================================================================
# Target rules for targets named test_carve3

# Build rule for target.
test_carve3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_carve3
.PHONY : test_carve3

# fast build rule for target.
test_carve3/fast:
	$(MAKE) -f CMakeFiles/test_carve3.dir/build.make CMakeFiles/test_carve3.dir/build
.PHONY : test_carve3/fast

#=============================================================================
# Target rules for targets named test_pipeflow

# Build rule for target.
test_pipeflow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_pipeflow
.PHONY : test_pipeflow

# fast build rule for target.
test_pipeflow/fast:
	$(MAKE) -f CMakeFiles/test_pipeflow.dir/build.make CMakeFiles/test_pipeflow.dir/build
.PHONY : test_pipeflow/fast

test_carve2.o: test_carve2.cpp.o

.PHONY : test_carve2.o

# target to build an object file
test_carve2.cpp.o:
	$(MAKE) -f CMakeFiles/test_carve2.dir/build.make CMakeFiles/test_carve2.dir/test_carve2.cpp.o
.PHONY : test_carve2.cpp.o

test_carve2.i: test_carve2.cpp.i

.PHONY : test_carve2.i

# target to preprocess a source file
test_carve2.cpp.i:
	$(MAKE) -f CMakeFiles/test_carve2.dir/build.make CMakeFiles/test_carve2.dir/test_carve2.cpp.i
.PHONY : test_carve2.cpp.i

test_carve2.s: test_carve2.cpp.s

.PHONY : test_carve2.s

# target to generate assembly for a file
test_carve2.cpp.s:
	$(MAKE) -f CMakeFiles/test_carve2.dir/build.make CMakeFiles/test_carve2.dir/test_carve2.cpp.s
.PHONY : test_carve2.cpp.s

test_carve3.o: test_carve3.cpp.o

.PHONY : test_carve3.o

# target to build an object file
test_carve3.cpp.o:
	$(MAKE) -f CMakeFiles/test_carve3.dir/build.make CMakeFiles/test_carve3.dir/test_carve3.cpp.o
.PHONY : test_carve3.cpp.o

test_carve3.i: test_carve3.cpp.i

.PHONY : test_carve3.i

# target to preprocess a source file
test_carve3.cpp.i:
	$(MAKE) -f CMakeFiles/test_carve3.dir/build.make CMakeFiles/test_carve3.dir/test_carve3.cpp.i
.PHONY : test_carve3.cpp.i

test_carve3.s: test_carve3.cpp.s

.PHONY : test_carve3.s

# target to generate assembly for a file
test_carve3.cpp.s:
	$(MAKE) -f CMakeFiles/test_carve3.dir/build.make CMakeFiles/test_carve3.dir/test_carve3.cpp.s
.PHONY : test_carve3.cpp.s

test_cavity.o: test_cavity.cpp.o

.PHONY : test_cavity.o

# target to build an object file
test_cavity.cpp.o:
	$(MAKE) -f CMakeFiles/test_cavity.dir/build.make CMakeFiles/test_cavity.dir/test_cavity.cpp.o
.PHONY : test_cavity.cpp.o

test_cavity.i: test_cavity.cpp.i

.PHONY : test_cavity.i

# target to preprocess a source file
test_cavity.cpp.i:
	$(MAKE) -f CMakeFiles/test_cavity.dir/build.make CMakeFiles/test_cavity.dir/test_cavity.cpp.i
.PHONY : test_cavity.cpp.i

test_cavity.s: test_cavity.cpp.s

.PHONY : test_cavity.s

# target to generate assembly for a file
test_cavity.cpp.s:
	$(MAKE) -f CMakeFiles/test_cavity.dir/build.make CMakeFiles/test_cavity.dir/test_cavity.cpp.s
.PHONY : test_cavity.cpp.s

test_pipeflow.o: test_pipeflow.cpp.o

.PHONY : test_pipeflow.o

# target to build an object file
test_pipeflow.cpp.o:
	$(MAKE) -f CMakeFiles/test_pipeflow.dir/build.make CMakeFiles/test_pipeflow.dir/test_pipeflow.cpp.o
.PHONY : test_pipeflow.cpp.o

test_pipeflow.i: test_pipeflow.cpp.i

.PHONY : test_pipeflow.i

# target to preprocess a source file
test_pipeflow.cpp.i:
	$(MAKE) -f CMakeFiles/test_pipeflow.dir/build.make CMakeFiles/test_pipeflow.dir/test_pipeflow.cpp.i
.PHONY : test_pipeflow.cpp.i

test_pipeflow.s: test_pipeflow.cpp.s

.PHONY : test_pipeflow.s

# target to generate assembly for a file
test_pipeflow.cpp.s:
	$(MAKE) -f CMakeFiles/test_pipeflow.dir/build.make CMakeFiles/test_pipeflow.dir/test_pipeflow.cpp.s
.PHONY : test_pipeflow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... test_cavity"
	@echo "... test_carve2"
	@echo "... rebuild_cache"
	@echo "... test_carve3"
	@echo "... test_pipeflow"
	@echo "... test_carve2.o"
	@echo "... test_carve2.i"
	@echo "... test_carve2.s"
	@echo "... test_carve3.o"
	@echo "... test_carve3.i"
	@echo "... test_carve3.s"
	@echo "... test_cavity.o"
	@echo "... test_cavity.i"
	@echo "... test_cavity.s"
	@echo "... test_pipeflow.o"
	@echo "... test_pipeflow.i"
	@echo "... test_pipeflow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

