# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pzhang/chen/permeable_bed

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pzhang/chen/permeable_bed

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pzhang/chen/permeable_bed/CMakeFiles /home/pzhang/chen/permeable_bed/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pzhang/chen/permeable_bed/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_cd_ga

# Build rule for target.
test_cd_ga: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cd_ga
.PHONY : test_cd_ga

# fast build rule for target.
test_cd_ga/fast:
	$(MAKE) -f CMakeFiles/test_cd_ga.dir/build.make CMakeFiles/test_cd_ga.dir/build
.PHONY : test_cd_ga/fast

#=============================================================================
# Target rules for targets named test_cd_bb

# Build rule for target.
test_cd_bb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cd_bb
.PHONY : test_cd_bb

# fast build rule for target.
test_cd_bb/fast:
	$(MAKE) -f CMakeFiles/test_cd_bb.dir/build.make CMakeFiles/test_cd_bb.dir/build
.PHONY : test_cd_bb/fast

#=============================================================================
# Target rules for targets named test_sc_ga

# Build rule for target.
test_sc_ga: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sc_ga
.PHONY : test_sc_ga

# fast build rule for target.
test_sc_ga/fast:
	$(MAKE) -f CMakeFiles/test_sc_ga.dir/build.make CMakeFiles/test_sc_ga.dir/build
.PHONY : test_sc_ga/fast

#=============================================================================
# Target rules for targets named test_sc_bb

# Build rule for target.
test_sc_bb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sc_bb
.PHONY : test_sc_bb

# fast build rule for target.
test_sc_bb/fast:
	$(MAKE) -f CMakeFiles/test_sc_bb.dir/build.make CMakeFiles/test_sc_bb.dir/build
.PHONY : test_sc_bb/fast

test_cd_bb.o: test_cd_bb.cpp.o

.PHONY : test_cd_bb.o

# target to build an object file
test_cd_bb.cpp.o:
	$(MAKE) -f CMakeFiles/test_cd_bb.dir/build.make CMakeFiles/test_cd_bb.dir/test_cd_bb.cpp.o
.PHONY : test_cd_bb.cpp.o

test_cd_bb.i: test_cd_bb.cpp.i

.PHONY : test_cd_bb.i

# target to preprocess a source file
test_cd_bb.cpp.i:
	$(MAKE) -f CMakeFiles/test_cd_bb.dir/build.make CMakeFiles/test_cd_bb.dir/test_cd_bb.cpp.i
.PHONY : test_cd_bb.cpp.i

test_cd_bb.s: test_cd_bb.cpp.s

.PHONY : test_cd_bb.s

# target to generate assembly for a file
test_cd_bb.cpp.s:
	$(MAKE) -f CMakeFiles/test_cd_bb.dir/build.make CMakeFiles/test_cd_bb.dir/test_cd_bb.cpp.s
.PHONY : test_cd_bb.cpp.s

test_cd_ga.o: test_cd_ga.cpp.o

.PHONY : test_cd_ga.o

# target to build an object file
test_cd_ga.cpp.o:
	$(MAKE) -f CMakeFiles/test_cd_ga.dir/build.make CMakeFiles/test_cd_ga.dir/test_cd_ga.cpp.o
.PHONY : test_cd_ga.cpp.o

test_cd_ga.i: test_cd_ga.cpp.i

.PHONY : test_cd_ga.i

# target to preprocess a source file
test_cd_ga.cpp.i:
	$(MAKE) -f CMakeFiles/test_cd_ga.dir/build.make CMakeFiles/test_cd_ga.dir/test_cd_ga.cpp.i
.PHONY : test_cd_ga.cpp.i

test_cd_ga.s: test_cd_ga.cpp.s

.PHONY : test_cd_ga.s

# target to generate assembly for a file
test_cd_ga.cpp.s:
	$(MAKE) -f CMakeFiles/test_cd_ga.dir/build.make CMakeFiles/test_cd_ga.dir/test_cd_ga.cpp.s
.PHONY : test_cd_ga.cpp.s

test_sc_bb.o: test_sc_bb.cpp.o

.PHONY : test_sc_bb.o

# target to build an object file
test_sc_bb.cpp.o:
	$(MAKE) -f CMakeFiles/test_sc_bb.dir/build.make CMakeFiles/test_sc_bb.dir/test_sc_bb.cpp.o
.PHONY : test_sc_bb.cpp.o

test_sc_bb.i: test_sc_bb.cpp.i

.PHONY : test_sc_bb.i

# target to preprocess a source file
test_sc_bb.cpp.i:
	$(MAKE) -f CMakeFiles/test_sc_bb.dir/build.make CMakeFiles/test_sc_bb.dir/test_sc_bb.cpp.i
.PHONY : test_sc_bb.cpp.i

test_sc_bb.s: test_sc_bb.cpp.s

.PHONY : test_sc_bb.s

# target to generate assembly for a file
test_sc_bb.cpp.s:
	$(MAKE) -f CMakeFiles/test_sc_bb.dir/build.make CMakeFiles/test_sc_bb.dir/test_sc_bb.cpp.s
.PHONY : test_sc_bb.cpp.s

test_sc_ga.o: test_sc_ga.cpp.o

.PHONY : test_sc_ga.o

# target to build an object file
test_sc_ga.cpp.o:
	$(MAKE) -f CMakeFiles/test_sc_ga.dir/build.make CMakeFiles/test_sc_ga.dir/test_sc_ga.cpp.o
.PHONY : test_sc_ga.cpp.o

test_sc_ga.i: test_sc_ga.cpp.i

.PHONY : test_sc_ga.i

# target to preprocess a source file
test_sc_ga.cpp.i:
	$(MAKE) -f CMakeFiles/test_sc_ga.dir/build.make CMakeFiles/test_sc_ga.dir/test_sc_ga.cpp.i
.PHONY : test_sc_ga.cpp.i

test_sc_ga.s: test_sc_ga.cpp.s

.PHONY : test_sc_ga.s

# target to generate assembly for a file
test_sc_ga.cpp.s:
	$(MAKE) -f CMakeFiles/test_sc_ga.dir/build.make CMakeFiles/test_sc_ga.dir/test_sc_ga.cpp.s
.PHONY : test_sc_ga.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_cd_ga"
	@echo "... test_cd_bb"
	@echo "... test_sc_ga"
	@echo "... test_sc_bb"
	@echo "... test_cd_bb.o"
	@echo "... test_cd_bb.i"
	@echo "... test_cd_bb.s"
	@echo "... test_cd_ga.o"
	@echo "... test_cd_ga.i"
	@echo "... test_cd_ga.s"
	@echo "... test_sc_bb.o"
	@echo "... test_sc_bb.i"
	@echo "... test_sc_bb.s"
	@echo "... test_sc_ga.o"
	@echo "... test_sc_ga.i"
	@echo "... test_sc_ga.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

